plugins {
	id 'gg.norisk.loom'
}

java {
	sourceCompatibility = JavaVersion.VERSION_1_8
	targetCompatibility = JavaVersion.VERSION_1_8
}

base {
	archivesName = project.archives_base_name
}

version = project.mod_version
group = project.maven_group

loom {
	forge {
		pack200Provider = new dev.architectury.pack200.java.Pack200Adapter()
	}
}

repositories {
	maven {
		url = 'https://maven.minecraftforge.net/'
		metadataSources {
			artifact()
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:1.7.10"
	mappings "de.oceanlabs.mcp:mcp_stable:12-1.7.10"
	forge "net.minecraftforge:forge:1.7.10-10.13.4.1614-1.7.10"
}

tasks.withType(JavaCompile).configureEach {
	it.options.encoding = "UTF-8"
	it.options.release = 8
}
